/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fittrack;

/**
 *
 * @author henni
 */
public class LogOnGUI extends javax.swing.JFrame {

    /**
     * Creates new form LogOnGUI
     */
    public LogOnGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblUserTypeLabel = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox<>();
        lblUsernameLabel = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        lblPasswordLabel = new javax.swing.JLabel();
        pwfPassword = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        btnLogOn = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Member" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FitTrackPro-LogOn");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().setBackground(Theme.BACKGROUND);

        lblHeading.setText("Log On");
        lblHeading.setFont(Theme.HEADING_FONT);
        lblHeading.setForeground(Theme.ACCENT_DARK_BLUE);
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 30));

        lblUserTypeLabel.setText("User Type:");
        lblUserTypeLabel.setFont(Theme.LABEL_FONT);
        getContentPane().add(lblUserTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 18));

        getContentPane().add(cmbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 25));

        lblUsernameLabel.setText("Username:");
        lblUsernameLabel.setFont(Theme.LABEL_FONT);
        getContentPane().add(lblUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 150, 18));

        getContentPane().add(txfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 180, 25));

        lblPasswordLabel.setText("Password:");
        lblPasswordLabel.setFont(Theme.LABEL_FONT);
        getContentPane().add(lblPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 18));

        getContentPane().add(pwfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 25));

        lblError.setText(" ");
        lblError.setFont(Theme.MESSAGE_FONT);
        lblError.setForeground(Theme.ERROR_RED);
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 212, 280, 20));

        btnLogOn.setText("Log On");
        btnLogOn.setFont(Theme.BUTTON_FONT);
        btnLogOn.setBackground(Theme.ACCENT_DARK_BLUE);
        btnLogOn.setForeground(java.awt.Color.WHITE);
        btnLogOn.setOpaque(true);
        btnLogOn.setBorderPainted(false);
        btnLogOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOnActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 30));

        btnHelp.setText("Help");
        btnHelp.setFont(Theme.BUTTON_FONT);
        btnHelp.setBackground(Theme.ACCENT_DARK_BLUE);
        btnHelp.setForeground(java.awt.Color.WHITE);
        btnHelp.setOpaque(true);
        btnHelp.setBorderPainted(false);
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 90, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOnActionPerformed
    String userType = (String) cmbUserType.getSelectedItem();
    String username = txfUsername.getText();
    String password = new String(pwfPassword.getPassword());
    lblError.setText("");

    if (userType.equals("Administrator")) {
        checkAdministrator(username, password);
    } else if (userType.equals("Member")) {
        checkMember(username, password);
    }
}//GEN-LAST:event_btnLogOnActionPerformed

private void checkAdministrator(String username, String password) {
    int pos = Manager.userArray.searchUserName(username);
    if (pos == -1) {
        lblError.setText("User not found");
        return;
    }
    User user = Manager.userArray.getUser(pos);
    if (user.getPassword().equals(password) && user.getUserType().equals("Administrator")) {
        Manager.currentUser = pos;
        new MainGUI().setVisible(true);
        this.dispose();
    } else {
        lblError.setText("Incorrect username or password");
        txfUsername.setText("");
        pwfPassword.setText("");
    }
}

private void checkMember(String username, String password) {
    int pos = Manager.userArray.searchUserName(username);
    if (pos == -1) {
        lblError.setText("User not found");
        return;
    }
    User user = Manager.userArray.getUser(pos);
    if (user.getPassword().equals(password) && user.getUserType().equals("Member")) {
        Manager.currentUser = pos;
        new MainGUI().setVisible(true);
        this.dispose();
    } else {
        lblError.setText("Incorrect username or password");
        txfUsername.setText("");
        pwfPassword.setText("");
    }
}

private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Select your user type, enter your username and password, then click Log On.");
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogOnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogOnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogOnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogOnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogOnGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogOn;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblPasswordLabel;
    private javax.swing.JLabel lblUserTypeLabel;
    private javax.swing.JLabel lblUsernameLabel;
    private javax.swing.JPasswordField pwfPassword;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
