/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fittrack;

/**
 *
 * @author henni
 */
public class MainGUI extends javax.swing.JFrame {

    private int memberIndex = 0;
    private int selectedAttendanceMemberIndex = -1;
    private int selectedProgressMemberIndex = -1;
    private int selectedMembershipIndex = -1;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();

        User loggedInUser = Manager.userArray.getUser(Manager.currentUser);
        if (loggedInUser.getUserType().equals("Member")) {
            tabMain.setEnabledAt(0, false);  // Members — admin only
            tabMain.setEnabledAt(1, false);  // Memberships — admin only
            tabMain.setEnabledAt(5, false);  // Reports — admin only
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        scrMembers = new javax.swing.JScrollPane();
        txaMembers = new javax.swing.JTextArea();
        btnSortMembers = new javax.swing.JButton();
        txfMemberID = new javax.swing.JTextField();
        txfMemberName = new javax.swing.JTextField();
        txfMemberSurname = new javax.swing.JTextField();
        txfMemberContact = new javax.swing.JTextField();
        txfMemberJoinDate = new javax.swing.JTextField();
        txfMemberHeight = new javax.swing.JTextField();
        txfMemberCurrentWeight = new javax.swing.JTextField();
        txfMemberBMI = new javax.swing.JTextField();
        txfMemberFitnessGoal = new javax.swing.JTextField();
        btnAddMember = new javax.swing.JButton();
        btnSaveContact = new javax.swing.JButton();
        lblEditMemberStatus = new javax.swing.JLabel();
        lblMemberActiveStatus = new javax.swing.JLabel();
        btnToggleActive = new javax.swing.JButton();
        btnFirstMember = new javax.swing.JButton();
        btnPrevMember = new javax.swing.JButton();
        btnNextMember = new javax.swing.JButton();
        btnLastMember = new javax.swing.JButton();
        cmbAttendanceMember = new javax.swing.JComboBox<>();
        lblAttendanceMemberID = new javax.swing.JLabel();
        btnCheckIn = new javax.swing.JButton();
        lblCheckInStatus = new javax.swing.JLabel();
        cmbProgressMember = new javax.swing.JComboBox<>();
        lblProgressMemberID = new javax.swing.JLabel();
        txfBodyWeight = new javax.swing.JTextField();
        txfMeasurements = new javax.swing.JTextField();
        txfProgressNotes = new javax.swing.JTextField();
        btnRecordProgress = new javax.swing.JButton();
        lblProgressStatus = new javax.swing.JLabel();
        cmbTrainingPlan = new javax.swing.JComboBox<>();
        lblTrainingPlanID = new javax.swing.JLabel();
        lblPlanBadge = new javax.swing.JLabel();
        cmbMembership = new javax.swing.JComboBox<>();
        lblMembershipInfo = new javax.swing.JLabel();
        cmbPaymentStatus = new javax.swing.JComboBox<>();
        btnUpdatePaymentStatus = new javax.swing.JButton();
        lblPaymentStatusMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        scrMemberships = new javax.swing.JScrollPane();
        txaMemberships = new javax.swing.JTextArea();
        btnSortMemberships = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FitTrackPro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.setBackground(Theme.BACKGROUND);

        txaMembers.setEditable(false);
        txaMembers.setColumns(20);
        txaMembers.setRows(5);
        scrMembers.setViewportView(txaMembers);

        jPanel1.add(scrMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 140));

        btnSortMembers.setText("Sort by Surname");
        btnSortMembers.setFont(Theme.BUTTON_FONT);
        btnSortMembers.setBackground(Theme.ACCENT_DARK_BLUE);
        btnSortMembers.setForeground(java.awt.Color.WHITE);
        btnSortMembers.setOpaque(true);
        btnSortMembers.setBorderPainted(false);
        btnSortMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortMembersActionPerformed(evt);
            }
        });
        jPanel1.add(btnSortMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 150, 28));

        btnAddMember.setText("Add Member");
        btnAddMember.setFont(Theme.BUTTON_FONT);
        btnAddMember.setBackground(Theme.ACCENT_DARK_BLUE);
        btnAddMember.setForeground(java.awt.Color.WHITE);
        btnAddMember.setOpaque(true);
        btnAddMember.setBorderPainted(false);
        btnAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemberActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 155, 120, 28));

        javax.swing.JLabel lblMemberIDLabel = new javax.swing.JLabel("Member ID:");
        lblMemberIDLabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 100, 18));
        txfMemberID.setEditable(false);
        jPanel1.add(txfMemberID, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 195, 170, 22));

        javax.swing.JLabel lblMemberNameLabel = new javax.swing.JLabel("Name:");
        lblMemberNameLabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, 100, 18));
        txfMemberName.setEditable(false);
        jPanel1.add(txfMemberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 221, 170, 22));

        javax.swing.JLabel lblMemberSurnameLabel = new javax.swing.JLabel("Surname:");
        lblMemberSurnameLabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberSurnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 247, 100, 18));
        txfMemberSurname.setEditable(false);
        jPanel1.add(txfMemberSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 247, 170, 22));

        javax.swing.JLabel lblMemberContactLabel = new javax.swing.JLabel("Contact:");
        lblMemberContactLabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 273, 100, 18));
        jPanel1.add(txfMemberContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 273, 120, 22));

        btnSaveContact.setText("Save");
        btnSaveContact.setFont(Theme.BUTTON_FONT);
        btnSaveContact.setBackground(Theme.ACCENT_DARK_BLUE);
        btnSaveContact.setForeground(java.awt.Color.WHITE);
        btnSaveContact.setOpaque(true);
        btnSaveContact.setBorderPainted(false);
        btnSaveContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveContactActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 273, 55, 22));

        javax.swing.JLabel lblMemberJoinDateLabel = new javax.swing.JLabel("Join Date:");
        lblMemberJoinDateLabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberJoinDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, 100, 18));
        txfMemberJoinDate.setEditable(false);
        jPanel1.add(txfMemberJoinDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 299, 170, 22));

        javax.swing.JLabel lblMemberHeightLabel = new javax.swing.JLabel("Height (m):");
        lblMemberHeightLabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberHeightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 195, 100, 18));
        txfMemberHeight.setEditable(false);
        jPanel1.add(txfMemberHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 195, 160, 22));

        javax.swing.JLabel lblMemberCurrentWeightLabel = new javax.swing.JLabel("Current Weight (kg):");
        lblMemberCurrentWeightLabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberCurrentWeightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 221, 100, 18));
        txfMemberCurrentWeight.setEditable(false);
        jPanel1.add(txfMemberCurrentWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 221, 160, 22));

        javax.swing.JLabel lblMemberBMILabel = new javax.swing.JLabel("BMI:");
        lblMemberBMILabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberBMILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 247, 100, 18));
        txfMemberBMI.setEditable(false);
        jPanel1.add(txfMemberBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 247, 160, 22));

        javax.swing.JLabel lblMemberFitnessGoalLabel = new javax.swing.JLabel("Fitness Goal:");
        lblMemberFitnessGoalLabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberFitnessGoalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 273, 100, 18));
        txfMemberFitnessGoal.setEditable(false);
        jPanel1.add(txfMemberFitnessGoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 273, 160, 22));

        javax.swing.JLabel lblMemberStatusLabel = new javax.swing.JLabel("Status:");
        lblMemberStatusLabel.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 299, 60, 18));

        lblMemberActiveStatus.setFont(Theme.LABEL_FONT);
        jPanel1.add(lblMemberActiveStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 299, 70, 18));

        btnToggleActive.setFont(Theme.BUTTON_FONT);
        btnToggleActive.setBackground(Theme.ACCENT_DARK_BLUE);
        btnToggleActive.setForeground(java.awt.Color.WHITE);
        btnToggleActive.setOpaque(true);
        btnToggleActive.setBorderPainted(false);
        btnToggleActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleActiveActionPerformed(evt);
            }
        });
        jPanel1.add(btnToggleActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 298, 120, 22));

        javax.swing.JPanel pnlMemberNav = new javax.swing.JPanel();
        pnlMemberNav.setBackground(Theme.BACKGROUND);

        btnFirstMember.setText("<<");
        btnFirstMember.setFont(Theme.BUTTON_FONT);
        btnFirstMember.setBackground(Theme.ACCENT_DARK_BLUE);
        btnFirstMember.setForeground(java.awt.Color.WHITE);
        btnFirstMember.setOpaque(true);
        btnFirstMember.setBorderPainted(false);
        btnFirstMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstMemberActionPerformed(evt);
            }
        });
        pnlMemberNav.add(btnFirstMember);

        btnPrevMember.setText("<");
        btnPrevMember.setFont(Theme.BUTTON_FONT);
        btnPrevMember.setBackground(Theme.ACCENT_DARK_BLUE);
        btnPrevMember.setForeground(java.awt.Color.WHITE);
        btnPrevMember.setOpaque(true);
        btnPrevMember.setBorderPainted(false);
        btnPrevMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevMemberActionPerformed(evt);
            }
        });
        pnlMemberNav.add(btnPrevMember);

        btnNextMember.setText(">");
        btnNextMember.setFont(Theme.BUTTON_FONT);
        btnNextMember.setBackground(Theme.ACCENT_DARK_BLUE);
        btnNextMember.setForeground(java.awt.Color.WHITE);
        btnNextMember.setOpaque(true);
        btnNextMember.setBorderPainted(false);
        btnNextMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextMemberActionPerformed(evt);
            }
        });
        pnlMemberNav.add(btnNextMember);

        btnLastMember.setText(">>");
        btnLastMember.setFont(Theme.BUTTON_FONT);
        btnLastMember.setBackground(Theme.ACCENT_DARK_BLUE);
        btnLastMember.setForeground(java.awt.Color.WHITE);
        btnLastMember.setOpaque(true);
        btnLastMember.setBorderPainted(false);
        btnLastMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastMemberActionPerformed(evt);
            }
        });
        pnlMemberNav.add(btnLastMember);

        jPanel1.add(pnlMemberNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 300, 40));

        lblEditMemberStatus.setText(" ");
        lblEditMemberStatus.setFont(Theme.MESSAGE_FONT);
        jPanel1.add(lblEditMemberStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 375, 500, 20));

        tabMain.addTab("Members", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.setBackground(Theme.BACKGROUND);

        txaMemberships.setEditable(false);
        txaMemberships.setColumns(20);
        txaMemberships.setRows(5);
        scrMemberships.setViewportView(txaMemberships);

        jPanel2.add(scrMemberships, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 140));

        btnSortMemberships.setText("Sort by End Date");
        btnSortMemberships.setFont(Theme.BUTTON_FONT);
        btnSortMemberships.setBackground(Theme.ACCENT_DARK_BLUE);
        btnSortMemberships.setForeground(java.awt.Color.WHITE);
        btnSortMemberships.setOpaque(true);
        btnSortMemberships.setBorderPainted(false);
        btnSortMemberships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortMembershipsActionPerformed(evt);
            }
        });
        jPanel2.add(btnSortMemberships, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 150, 28));

        javax.swing.JLabel lblSelectMembership = new javax.swing.JLabel("Select Membership:");
        lblSelectMembership.setFont(Theme.LABEL_FONT);
        jPanel2.add(lblSelectMembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 150, 18));

        cmbMembership.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbMembershipFocusGained(evt);
            }
        });
        cmbMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMembershipActionPerformed(evt);
            }
        });
        jPanel2.add(cmbMembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, 400, 25));

        lblMembershipInfo.setText(" ");
        lblMembershipInfo.setFont(Theme.LABEL_FONT);
        jPanel2.add(lblMembershipInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 247, 500, 20));

        javax.swing.JLabel lblNewPaymentStatus = new javax.swing.JLabel("New Payment Status:");
        lblNewPaymentStatus.setFont(Theme.LABEL_FONT);
        jPanel2.add(lblNewPaymentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 18));

        cmbPaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paid", "Pending", "Overdue" }));
        jPanel2.add(cmbPaymentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 150, 25));

        btnUpdatePaymentStatus.setText("Update Status");
        btnUpdatePaymentStatus.setFont(Theme.BUTTON_FONT);
        btnUpdatePaymentStatus.setBackground(Theme.ACCENT_DARK_BLUE);
        btnUpdatePaymentStatus.setForeground(java.awt.Color.WHITE);
        btnUpdatePaymentStatus.setOpaque(true);
        btnUpdatePaymentStatus.setBorderPainted(false);
        btnUpdatePaymentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePaymentStatusActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdatePaymentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 315, 150, 30));

        lblPaymentStatusMessage.setText(" ");
        lblPaymentStatusMessage.setFont(Theme.MESSAGE_FONT);
        jPanel2.add(lblPaymentStatusMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 352, 400, 20));

        tabMain.addTab("Memberships", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.setBackground(Theme.BACKGROUND);

        javax.swing.JLabel lblSelectMemberAttendance = new javax.swing.JLabel("Select Member:");
        lblSelectMemberAttendance.setFont(Theme.LABEL_FONT);
        jPanel3.add(lblSelectMemberAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 150, 18));

        cmbAttendanceMember.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbAttendanceMemberFocusGained(evt);
            }
        });
        cmbAttendanceMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAttendanceMemberActionPerformed(evt);
            }
        });
        jPanel3.add(cmbAttendanceMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 250, 25));

        lblAttendanceMemberID.setText("Member ID: ---");
        lblAttendanceMemberID.setFont(Theme.LABEL_FONT);
        jPanel3.add(lblAttendanceMemberID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 250, 20));

        btnCheckIn.setText("Check In");
        btnCheckIn.setFont(Theme.BUTTON_FONT);
        btnCheckIn.setBackground(Theme.ACCENT_DARK_BLUE);
        btnCheckIn.setForeground(java.awt.Color.WHITE);
        btnCheckIn.setOpaque(true);
        btnCheckIn.setBorderPainted(false);
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });
        jPanel3.add(btnCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 30));

        lblCheckInStatus.setText(" ");
        lblCheckInStatus.setFont(Theme.MESSAGE_FONT);
        jPanel3.add(lblCheckInStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 400, 20));

        tabMain.addTab("Attendance", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.setBackground(Theme.BACKGROUND);

        javax.swing.JLabel lblSelectPlan = new javax.swing.JLabel("Select Plan:");
        lblSelectPlan.setFont(Theme.LABEL_FONT);
        jPanel4.add(lblSelectPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 150, 18));

        cmbTrainingPlan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbTrainingPlanFocusGained(evt);
            }
        });
        cmbTrainingPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTrainingPlanActionPerformed(evt);
            }
        });
        jPanel4.add(cmbTrainingPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 250, 25));

        lblTrainingPlanID.setText("Plan ID: ---");
        lblTrainingPlanID.setFont(Theme.LABEL_FONT);
        jPanel4.add(lblTrainingPlanID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 250, 20));

        lblPlanBadge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(lblPlanBadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, 140, 60));

        tabMain.addTab("Training Plans", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.setBackground(Theme.BACKGROUND);

        javax.swing.JLabel lblSelectMemberProgress = new javax.swing.JLabel("Select Member:");
        lblSelectMemberProgress.setFont(Theme.LABEL_FONT);
        jPanel5.add(lblSelectMemberProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 150, 18));

        cmbProgressMember.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbProgressMemberFocusGained(evt);
            }
        });
        cmbProgressMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProgressMemberActionPerformed(evt);
            }
        });
        jPanel5.add(cmbProgressMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 250, 25));

        lblProgressMemberID.setText("Member ID: ---");
        lblProgressMemberID.setFont(Theme.LABEL_FONT);
        jPanel5.add(lblProgressMemberID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 250, 20));

        javax.swing.JLabel lblBodyWeight = new javax.swing.JLabel("Body Weight (kg):");
        lblBodyWeight.setFont(Theme.LABEL_FONT);
        jPanel5.add(lblBodyWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 18));
        jPanel5.add(txfBodyWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 100, 22));

        javax.swing.JLabel lblMeasurements = new javax.swing.JLabel("Measurements:");
        lblMeasurements.setFont(Theme.LABEL_FONT);
        jPanel5.add(lblMeasurements, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 18));
        jPanel5.add(txfMeasurements, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 250, 22));

        javax.swing.JLabel lblProgressNotes = new javax.swing.JLabel("Notes:");
        lblProgressNotes.setFont(Theme.LABEL_FONT);
        jPanel5.add(lblProgressNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 18));
        jPanel5.add(txfProgressNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 250, 22));

        btnRecordProgress.setText("Record Progress");
        btnRecordProgress.setFont(Theme.BUTTON_FONT);
        btnRecordProgress.setBackground(Theme.ACCENT_DARK_BLUE);
        btnRecordProgress.setForeground(java.awt.Color.WHITE);
        btnRecordProgress.setOpaque(true);
        btnRecordProgress.setBorderPainted(false);
        btnRecordProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordProgressActionPerformed(evt);
            }
        });
        jPanel5.add(btnRecordProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 150, 30));

        lblProgressStatus.setText(" ");
        lblProgressStatus.setFont(Theme.MESSAGE_FONT);
        jPanel5.add(lblProgressStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 232, 400, 20));

        tabMain.addTab("Progress", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.setBackground(Theme.BACKGROUND);
        tabMain.addTab("Reports", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.setBackground(Theme.BACKGROUND);
        tabMain.addTab("Help", jPanel7);

        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(tabMain, java.awt.BorderLayout.CENTER);

        setSize(620, 480);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        ((javax.swing.text.DefaultCaret) txaMembers.getCaret()).setUpdatePolicy(javax.swing.text.DefaultCaret.NEVER_UPDATE);
        ((javax.swing.text.DefaultCaret) txaMemberships.getCaret()).setUpdatePolicy(javax.swing.text.DefaultCaret.NEVER_UPDATE);

        txaMembers.setText(Manager.memberArray.toString());
        txaMemberships.setText(Manager.membershipArray.toString());

        updateMemberFields(memberIndex);

        populateAttendanceMemberCombo();
        populateProgressMemberCombo();
        populateTrainingPlanCombo();
        populateMembershipCombo();
    }

    private void btnSortMembersActionPerformed(java.awt.event.ActionEvent evt) {
        Manager.memberArray.sortBySurname();
        txaMembers.setText(Manager.memberArray.toString());
    }

    private void btnSortMembershipsActionPerformed(java.awt.event.ActionEvent evt) {
        Manager.membershipArray.sortByEndDate();
        txaMemberships.setText(Manager.membershipArray.toString());
    }

    private void cmbMembershipFocusGained(java.awt.event.FocusEvent evt) {
        populateMembershipCombo();
    }

    private void populateMembershipCombo() {
        cmbMembership.removeAllItems();
        cmbMembership.addItem("Select option");
        for (int i = 0; i < Manager.membershipArray.getSize(); i++) {
            Membership ms = Manager.membershipArray.getMembership(i);
            int memberPos = Manager.memberArray.searchFirst(ms.getMemberID());
            String memberName = (memberPos == -1) ? ms.getMemberID() : Manager.memberArray.getMember(memberPos).getFullName();
            cmbMembership.addItem(memberName + " - " + ms.getMembershipType() + " (" + ms.getMembershipID() + ")");
        }
    }

    private void cmbMembershipActionPerformed(java.awt.event.ActionEvent evt) {
        int index = cmbMembership.getSelectedIndex();
        if (index <= 0) {
            selectedMembershipIndex = -1;
            lblMembershipInfo.setText(" ");
            return;
        }
        selectedMembershipIndex = index - 1;
        Membership ms = Manager.membershipArray.getMembership(selectedMembershipIndex);
        lblMembershipInfo.setText("Start: " + ms.getStartDate() + " | End: " + ms.getEndDate()
                + " | Current Status: " + ms.getPaymentStatus());
        cmbPaymentStatus.setSelectedItem(ms.getPaymentStatus());
    }

    private void btnUpdatePaymentStatusActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedMembershipIndex == -1) {
            lblPaymentStatusMessage.setForeground(Theme.ERROR_RED);
            lblPaymentStatusMessage.setText("Select a membership first.");
            return;
        }

        Membership ms = Manager.membershipArray.getMembership(selectedMembershipIndex);
        String newStatus = (String) cmbPaymentStatus.getSelectedItem();
        ms.setPaymentStatus(newStatus);
        Manager.membershipArray.saveToFile();

        txaMemberships.setText(Manager.membershipArray.toString());
        lblMembershipInfo.setText("Start: " + ms.getStartDate() + " | End: " + ms.getEndDate()
                + " | Current Status: " + ms.getPaymentStatus());

        lblPaymentStatusMessage.setForeground(Theme.SUCCESS_GREEN);
        lblPaymentStatusMessage.setText("Payment status updated to " + newStatus + " for " + ms.getMembershipID());
    }

    private void updateMemberFields(int pos) {
        Member m = Manager.memberArray.getMember(pos);
        txfMemberID.setText(m.getMemberID());
        txfMemberName.setText(m.getName());
        txfMemberSurname.setText(m.getSurname());
        txfMemberContact.setText(m.getContactDetails());
        txfMemberJoinDate.setText(m.getJoinDate().toString());
        txfMemberHeight.setText(String.valueOf(m.getHeight()));
        txfMemberCurrentWeight.setText(String.valueOf(m.getCurrentWeight()));
        txfMemberBMI.setText(String.valueOf(m.getBmi()));
        txfMemberFitnessGoal.setText(m.getFitnessGoal());
        updateActiveStatusDisplay(m);
    }

    private void updateActiveStatusDisplay(Member m) {
        if (m.isActiveStatus()) {
            lblMemberActiveStatus.setForeground(Theme.SUCCESS_GREEN);
            lblMemberActiveStatus.setText("Active");
            btnToggleActive.setText("Deactivate");
        } else {
            lblMemberActiveStatus.setForeground(Theme.ERROR_RED);
            lblMemberActiveStatus.setText("Inactive");
            btnToggleActive.setText("Activate");
        }
    }

    private void btnAddMemberActionPerformed(java.awt.event.ActionEvent evt) {
        showAddMemberDialog();
    }

    private void showAddMemberDialog() {
        final javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Add Member", true);
        dialog.setLayout(new java.awt.BorderLayout(10, 10));

        javax.swing.JPanel fieldsPanel = new javax.swing.JPanel(new java.awt.GridLayout(0, 2, 8, 8));

        final javax.swing.JTextField fldName = new javax.swing.JTextField();
        final javax.swing.JTextField fldSurname = new javax.swing.JTextField();
        final javax.swing.JTextField fldDateOfBirth = new javax.swing.JTextField();
        final javax.swing.JTextField fldContact = new javax.swing.JTextField();
        final javax.swing.JTextField fldHeight = new javax.swing.JTextField();
        final javax.swing.JTextField fldStartingWeight = new javax.swing.JTextField();
        final javax.swing.JTextField fldFitnessGoal = new javax.swing.JTextField();
        final javax.swing.JComboBox<String> fldPlan = new javax.swing.JComboBox<>();
        fldPlan.addItem("Select option");
        for (int i = 0; i < Manager.trainingPlanArray.getSize(); i++) {
            fldPlan.addItem(Manager.trainingPlanArray.getTrainingPlan(i).getPlanName());
        }

        fieldsPanel.add(new javax.swing.JLabel("Name:"));
        fieldsPanel.add(fldName);
        fieldsPanel.add(new javax.swing.JLabel("Surname:"));
        fieldsPanel.add(fldSurname);
        fieldsPanel.add(new javax.swing.JLabel("Date of Birth (yyyy-mm-dd):"));
        fieldsPanel.add(fldDateOfBirth);
        fieldsPanel.add(new javax.swing.JLabel("Contact:"));
        fieldsPanel.add(fldContact);
        fieldsPanel.add(new javax.swing.JLabel("Height (m):"));
        fieldsPanel.add(fldHeight);
        fieldsPanel.add(new javax.swing.JLabel("Starting Weight (kg):"));
        fieldsPanel.add(fldStartingWeight);
        fieldsPanel.add(new javax.swing.JLabel("Fitness Goal:"));
        fieldsPanel.add(fldFitnessGoal);
        fieldsPanel.add(new javax.swing.JLabel("Assigned Plan:"));
        fieldsPanel.add(fldPlan);

        dialog.add(fieldsPanel, java.awt.BorderLayout.CENTER);

        final javax.swing.JLabel lblDialogStatus = new javax.swing.JLabel(" ");
        lblDialogStatus.setFont(Theme.MESSAGE_FONT);

        javax.swing.JButton btnCreate = new javax.swing.JButton("Create");
        btnCreate.setFont(Theme.BUTTON_FONT);
        btnCreate.setBackground(Theme.ACCENT_DARK_BLUE);
        btnCreate.setForeground(java.awt.Color.WHITE);
        btnCreate.setOpaque(true);
        btnCreate.setBorderPainted(false);

        javax.swing.JButton btnCancel = new javax.swing.JButton("Cancel");

        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String name = fldName.getText().trim();
                String surname = fldSurname.getText().trim();
                String contact = fldContact.getText().trim();
                String fitnessGoal = fldFitnessGoal.getText().trim();

                if (name.isEmpty() || surname.isEmpty() || contact.isEmpty() || fitnessGoal.isEmpty()) {
                    lblDialogStatus.setForeground(Theme.ERROR_RED);
                    lblDialogStatus.setText("All fields are required.");
                    return;
                }
                if (contact.contains("#") || contact.contains(";")) {
                    lblDialogStatus.setForeground(Theme.ERROR_RED);
                    lblDialogStatus.setText("Contact cannot contain # or ;");
                    return;
                }

                java.time.LocalDate dateOfBirth;
                try {
                    dateOfBirth = java.time.LocalDate.parse(fldDateOfBirth.getText().trim());
                } catch (java.time.format.DateTimeParseException e) {
                    lblDialogStatus.setForeground(Theme.ERROR_RED);
                    lblDialogStatus.setText("Date of birth must be in yyyy-mm-dd format.");
                    return;
                }

                double height;
                double startingWeight;
                try {
                    height = Double.parseDouble(fldHeight.getText().trim());
                    startingWeight = Double.parseDouble(fldStartingWeight.getText().trim());
                } catch (NumberFormatException e) {
                    lblDialogStatus.setForeground(Theme.ERROR_RED);
                    lblDialogStatus.setText("Height and starting weight must be numbers.");
                    return;
                }
                if (height <= 0) {
                    lblDialogStatus.setForeground(Theme.ERROR_RED);
                    lblDialogStatus.setText("Height must be greater than zero.");
                    return;
                }

                int planIndex = fldPlan.getSelectedIndex();
                if (planIndex <= 0) {
                    lblDialogStatus.setForeground(Theme.ERROR_RED);
                    lblDialogStatus.setText("Select a training plan.");
                    return;
                }
                String assignedPlanID = Manager.trainingPlanArray.getTrainingPlan(planIndex - 1).getPlanID();

                String newID = Manager.memberArray.generateNextMemberID();
                double bmi = startingWeight / (height * height);

                Member newMember = new Member(newID, name, surname, dateOfBirth, contact,
                        java.time.LocalDate.now(), true, height, startingWeight, startingWeight,
                        bmi, fitnessGoal, assignedPlanID, "");

                Manager.memberArray.addMember(newMember);
                Manager.memberArray.saveToFile();

                txaMembers.setText(Manager.memberArray.toString());
                memberIndex = Manager.memberArray.getSize() - 1;
                updateMemberFields(memberIndex);

                lblEditMemberStatus.setForeground(Theme.SUCCESS_GREEN);
                lblEditMemberStatus.setText("Added new member " + newMember.getFullName() + " (" + newID + ").");

                dialog.dispose();
            }
        });

        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog.dispose();
            }
        });

        javax.swing.JPanel buttonRow = new javax.swing.JPanel();
        buttonRow.add(btnCreate);
        buttonRow.add(btnCancel);

        javax.swing.JPanel bottomPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        bottomPanel.add(lblDialogStatus, java.awt.BorderLayout.NORTH);
        bottomPanel.add(buttonRow, java.awt.BorderLayout.SOUTH);
        dialog.add(bottomPanel, java.awt.BorderLayout.SOUTH);

        dialog.setSize(420, 340);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void btnToggleActiveActionPerformed(java.awt.event.ActionEvent evt) {
        Member m = Manager.memberArray.getMember(memberIndex);
        m.setActiveStatus(!m.isActiveStatus());
        Manager.memberArray.saveToFile();

        updateActiveStatusDisplay(m);
        txaMembers.setText(Manager.memberArray.toString());

        lblEditMemberStatus.setForeground(Theme.SUCCESS_GREEN);
        lblEditMemberStatus.setText(m.getFullName() + " is now " + (m.isActiveStatus() ? "Active" : "Inactive") + ".");
    }

    private void btnSaveContactActionPerformed(java.awt.event.ActionEvent evt) {
        String newContact = txfMemberContact.getText();
        if (newContact.contains("#") || newContact.contains(";")) {
            lblEditMemberStatus.setForeground(Theme.ERROR_RED);
            lblEditMemberStatus.setText("Contact details cannot contain # or ;");
            return;
        }

        Member m = Manager.memberArray.getMember(memberIndex);
        m.setContactDetails(newContact);
        Manager.memberArray.saveToFile();

        lblEditMemberStatus.setForeground(Theme.SUCCESS_GREEN);
        lblEditMemberStatus.setText("Contact details saved for " + m.getFullName() + ".");
    }

    private void btnFirstMemberActionPerformed(java.awt.event.ActionEvent evt) {
        memberIndex = 0;
        updateMemberFields(memberIndex);
    }

    private void btnPrevMemberActionPerformed(java.awt.event.ActionEvent evt) {
        if (memberIndex > 0) {
            memberIndex--;
            updateMemberFields(memberIndex);
        }
    }

    private void btnNextMemberActionPerformed(java.awt.event.ActionEvent evt) {
        if (memberIndex < Manager.memberArray.getSize() - 1) {
            memberIndex++;
            updateMemberFields(memberIndex);
        }
    }

    private void btnLastMemberActionPerformed(java.awt.event.ActionEvent evt) {
        memberIndex = Manager.memberArray.getSize() - 1;
        updateMemberFields(memberIndex);
    }

    private void cmbAttendanceMemberFocusGained(java.awt.event.FocusEvent evt) {
        populateAttendanceMemberCombo();
    }

    private void populateAttendanceMemberCombo() {
        cmbAttendanceMember.removeAllItems();
        cmbAttendanceMember.addItem("Select option");
        for (int i = 0; i < Manager.memberArray.getSize(); i++) {
            cmbAttendanceMember.addItem(Manager.memberArray.getMember(i).getFullName());
        }
    }

    private void cmbAttendanceMemberActionPerformed(java.awt.event.ActionEvent evt) {
        int index = cmbAttendanceMember.getSelectedIndex();
        if (index <= 0) {
            selectedAttendanceMemberIndex = -1;
            lblAttendanceMemberID.setText("Member ID: ---");
            return;
        }
        selectedAttendanceMemberIndex = index - 1;
        Member m = Manager.memberArray.getMember(selectedAttendanceMemberIndex);
        lblAttendanceMemberID.setText("Member ID: " + m.getMemberID());
    }

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedAttendanceMemberIndex == -1) {
            lblCheckInStatus.setForeground(Theme.ERROR_RED);
            lblCheckInStatus.setText("Select a member first.");
            return;
        }

        Member m = Manager.memberArray.getMember(selectedAttendanceMemberIndex);
        java.time.LocalDate today = java.time.LocalDate.now();

        if (Manager.attendanceArray.hasCheckInOnDate(m.getMemberID(), today)) {
            lblCheckInStatus.setForeground(Theme.ERROR_RED);
            lblCheckInStatus.setText(m.getFullName() + " has already checked in today.");
            return;
        }

        java.time.LocalTime now = java.time.LocalTime.now().truncatedTo(java.time.temporal.ChronoUnit.MINUTES);
        String newID = Manager.attendanceArray.generateNextAttendanceID();
        AttendanceRecord record = new AttendanceRecord(newID, m.getMemberID(), today, now);

        Manager.attendanceArray.addRecord(record);
        Manager.attendanceArray.saveToFile();

        lblCheckInStatus.setForeground(Theme.SUCCESS_GREEN);
        lblCheckInStatus.setText("Checked in: " + m.getFullName() + " (" + newID + ")");
    }

    private void cmbProgressMemberFocusGained(java.awt.event.FocusEvent evt) {
        populateProgressMemberCombo();
    }

    private void populateProgressMemberCombo() {
        cmbProgressMember.removeAllItems();
        cmbProgressMember.addItem("Select option");
        for (int i = 0; i < Manager.memberArray.getSize(); i++) {
            cmbProgressMember.addItem(Manager.memberArray.getMember(i).getFullName());
        }
    }

    private void cmbProgressMemberActionPerformed(java.awt.event.ActionEvent evt) {
        int index = cmbProgressMember.getSelectedIndex();
        if (index <= 0) {
            selectedProgressMemberIndex = -1;
            lblProgressMemberID.setText("Member ID: ---");
            return;
        }
        selectedProgressMemberIndex = index - 1;
        Member m = Manager.memberArray.getMember(selectedProgressMemberIndex);
        lblProgressMemberID.setText("Member ID: " + m.getMemberID());
    }

    private void btnRecordProgressActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedProgressMemberIndex == -1) {
            lblProgressStatus.setForeground(Theme.ERROR_RED);
            lblProgressStatus.setText("Select a member first.");
            return;
        }

        double bodyWeight;
        try {
            bodyWeight = Double.parseDouble(txfBodyWeight.getText());
        } catch (NumberFormatException e) {
            lblProgressStatus.setForeground(Theme.ERROR_RED);
            lblProgressStatus.setText("Body weight must be a number.");
            return;
        }

        Member m = Manager.memberArray.getMember(selectedProgressMemberIndex);
        String newID = Manager.progressArray.generateNextProgressID();
        ProgressRecord record = new ProgressRecord(newID, m.getMemberID(), java.time.LocalDate.now(),
                bodyWeight, txfMeasurements.getText(), txfProgressNotes.getText());

        Manager.progressArray.addRecord(record);
        Manager.progressArray.saveToFile();

        m.setCurrentWeight(bodyWeight);
        Manager.memberArray.saveToFile();

        txfBodyWeight.setText("");
        txfMeasurements.setText("");
        txfProgressNotes.setText("");

        lblProgressStatus.setForeground(Theme.SUCCESS_GREEN);
        lblProgressStatus.setText("Progress recorded for " + m.getFullName() + " (" + newID + ")");
    }

    private void cmbTrainingPlanFocusGained(java.awt.event.FocusEvent evt) {
        populateTrainingPlanCombo();
    }

    private void populateTrainingPlanCombo() {
        cmbTrainingPlan.removeAllItems();
        cmbTrainingPlan.addItem("Select option");
        for (int i = 0; i < Manager.trainingPlanArray.getSize(); i++) {
            cmbTrainingPlan.addItem(Manager.trainingPlanArray.getTrainingPlan(i).getPlanName());
        }
    }

    private void cmbTrainingPlanActionPerformed(java.awt.event.ActionEvent evt) {
        int index = cmbTrainingPlan.getSelectedIndex();
        if (index <= 0) {
            lblTrainingPlanID.setText("Plan ID: ---");
            lblPlanBadge.setIcon(null);
            return;
        }
        TrainingPlan p = Manager.trainingPlanArray.getTrainingPlan(index - 1);
        lblTrainingPlanID.setText("Plan ID: " + p.getPlanID());
        updatePlanBadge(p.getDifficulty());
    }

    private void updatePlanBadge(String difficulty) {
        String filename;
        if (difficulty.equals("Beginner")) {
            filename = "/images/beginner.png";
        } else if (difficulty.equals("Intermediate")) {
            filename = "/images/intermediate.png";
        } else {
            filename = "/images/advanced.png";
        }
        java.net.URL imgURL = getClass().getResource(filename);
        if (imgURL != null) {
            lblPlanBadge.setIcon(new javax.swing.ImageIcon(imgURL));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstMember;
    private javax.swing.JButton btnLastMember;
    private javax.swing.JButton btnNextMember;
    private javax.swing.JButton btnPrevMember;
    private javax.swing.JButton btnSortMemberships;
    private javax.swing.JButton btnSortMembers;
    private javax.swing.JTextField txfMemberID;
    private javax.swing.JTextField txfMemberName;
    private javax.swing.JTextField txfMemberSurname;
    private javax.swing.JTextField txfMemberContact;
    private javax.swing.JTextField txfMemberJoinDate;
    private javax.swing.JTextField txfMemberHeight;
    private javax.swing.JTextField txfMemberCurrentWeight;
    private javax.swing.JTextField txfMemberBMI;
    private javax.swing.JTextField txfMemberFitnessGoal;
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnSaveContact;
    private javax.swing.JLabel lblEditMemberStatus;
    private javax.swing.JLabel lblMemberActiveStatus;
    private javax.swing.JButton btnToggleActive;
    private javax.swing.JComboBox<String> cmbAttendanceMember;
    private javax.swing.JLabel lblAttendanceMemberID;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JLabel lblCheckInStatus;
    private javax.swing.JComboBox<String> cmbProgressMember;
    private javax.swing.JLabel lblProgressMemberID;
    private javax.swing.JTextField txfBodyWeight;
    private javax.swing.JTextField txfMeasurements;
    private javax.swing.JTextField txfProgressNotes;
    private javax.swing.JButton btnRecordProgress;
    private javax.swing.JLabel lblProgressStatus;
    private javax.swing.JComboBox<String> cmbTrainingPlan;
    private javax.swing.JLabel lblTrainingPlanID;
    private javax.swing.JLabel lblPlanBadge;
    private javax.swing.JComboBox<String> cmbMembership;
    private javax.swing.JLabel lblMembershipInfo;
    private javax.swing.JComboBox<String> cmbPaymentStatus;
    private javax.swing.JButton btnUpdatePaymentStatus;
    private javax.swing.JLabel lblPaymentStatusMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane scrMemberships;
    private javax.swing.JScrollPane scrMembers;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextArea txaMemberships;
    private javax.swing.JTextArea txaMembers;
    // End of variables declaration//GEN-END:variables
}
